pipeline {
    agent any
    tools{
    	maven 'maven3'
    }
    stages {
        stage('build') {
            steps {
                dir('DevOpsAssignment') {
                    bat 'mvn clean package'
                }
            }
        }
    }
}
