pipeline {
    agent any
    tools{
    maven "maven3"
    }
    stages {
        stage('Checkout') {
            steps {
               checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/komalsinghh/Springboot-Docker.git']])
                           }
        }
        stage('Build') {
            steps {
                dir('Docker-Springboot') {
                    sh 'mvn clean install'
                }
            }
        }
	stage('Build Docker Image') {
            steps {
                script {
                dir('Docker-Springboot') {
               		sh 'pwd'
                    sh 'ls -la'
                    sh 'ls -la .'
                    sh 'docker build -t komalsinghh/docker-springboot:latest .'
                }
                }
            }
        }
        
      stage('Push Docker Image to Docker Hub') {
            steps {
                script {
                   withCredentials([string(credentialsId: 'komaldockerhubpwd', variable: 'komaldockerhubpwd')]) {
  					 	sh 'docker login -u komalsinghh -p ${komaldockerhubpwd}'
					}
						
						sh 'docker image push komalsinghh/docker-springboot:latest'
					}

            }
      stage('SonarQube Scan') {
    		steps {
        		script {
            
            withSonarQubeEnv('sonarserver') {
              
               sh "mvn sonar:sonar"
            }
        }
    }
}
            
        }
    }
}
