pipeline {
    agent any
    tools{
    maven "maven3"
    }
    stages {
        stage('Checkout') {
            steps {
               checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/komalsinghh/Springboot-Docker.git']])
                           }
        }
        stage('Build') {
            steps {
                dir('Docker-Springboot') {
                    bat 'mvn clean install'
                }
            }
        }
	stage('Build Docker Image') {
            steps {
                script {
                withDockerRegistry(credentialsId: '6fac79f6-b4fe-4a06-9e5a-6143519f51cd') {
                    sh 'docker build -t komalsinghh/springboot-docker:latest .'
                }
                }
            }
        }
        
      stage('Push Docker Image to Docker Hub') {
            steps {
                script {
                   withDockerRegistry(credentialsId: '6fac79f6-b4fe-4a06-9e5a-6143519f51cd') {
  					 sh 'docker image push komalsinghh/springboot-docker:latest'
						}
					}

            }
        }
    }
}
